USE [relatorio de vendas]
GO

/****** Objeto:  Table [dbo].[Negociações$]    Data do Script: 18/06/2026 01:46:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[vendas_de_produtos](
	[F1] [nvarchar](255) NULL,
	[F2] [datetime] NULL,
	[F3] [nvarchar](255) NULL,
	[F4] [nvarchar](255) NULL,
	[F5] [nvarchar](255) NULL,
	[F6] [money] NULL,
	[F7] [float] NULL,
	[F8] [money] NULL,
	[F9] [nvarchar](255) NULL,
	[F10] [nvarchar](255) NULL,
	[F11] [nvarchar](255) NULL,
	[F12] [nvarchar](255) NULL
) ON [PRIMARY]
GO


